wids: Change internet ping script. Add more ips.

diff --git a/widgets/utils/internet b/widgets/utils/internet
--- a/widgets/utils/internet
+++ b/widgets/utils/internet
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-wget -q --tries=10 --timeout=3 -O - https://google.com > /dev/null
+flag=0
 
-if [[ $? -eq 0 ]]; then
-    # Online
-    exit 1
-else
-    # Offline
-    exit 0
-fi
+ips=( 8.8.8.8 208.67.222.222 208.67.220.220 )
+
+for i in "${ips[@]}"
+do
+    echo "pinging: $i."
+    ping -W 1 -c 3 $i > /dev/null
+    if [[ "$?" -ne "0" ]]; then
+        echo "Fail to ping to $i."
+        flag=1
+    fi
+done
+
+echo $flag
